// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrwdesywaykeiuxxsekq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyd2Rlc3l3YXlrZWl1eHhzZWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzc5MzMsImV4cCI6MjA2NTcxMzkzM30.OO8P78UnPJJ04U4EOMQpOiaWIk4iGS7m6hD8FrXWjqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);